import 'package:geduc_rae_mobile/data/models/acao_model.dart';

AcaoModel criarAcaoTeste({
  String id = 'acao-1',
  String coordenadorId = 'coord-1',
  String coordenadorNome = 'Coordenadora Ana',
  int agentesTransito = 0,
  int equipeTerceirizada = 0,
  List<String> agenteEquipeIds = const [],
  List<String> agenteEquipeNomes = const [],
  List<String> terceirizadoEquipeIds = const [],
  List<String> terceirizadoEquipeNomes = const [],
  List<String> materialUtilizadoIds = const [],
  List<String> orgaoParticipanteIds = const [],
  String orgaoParticipanteId = '',
  int anoRAE = 2026,
}) {
  return AcaoModel(
    id: id,
    numeroRAE: '0001/2026',
    anoRAE: anoRAE,
    dataAcao: DateTime(2026, 8, 16),
    turno: 'Manhã',
    nomeAcao: 'Ação de teste',
    tipoAcao: 'Educativa',
    publicoEstimado: 20,
    publicoMinimo: 10,
    horaInicio: '08:00',
    pessoasAlcancadas: 15,
    veiculosAbordados: 4,
    credenciaisEmitidas: 0,
    metaAtingida: true,
    endereco: 'Rua de Teste',
    bairro: 'Centro',
    regional: 'Regional 1',
    latitude: -3.7,
    longitude: -38.5,
    coordenadorId: coordenadorId,
    coordenadorNome: coordenadorNome,
    agentesTransito: agentesTransito,
    equipeTerceirizada: equipeTerceirizada,
    agenteEquipeIds: agenteEquipeIds,
    agenteEquipeNomes: agenteEquipeNomes,
    terceirizadoEquipeIds: terceirizadoEquipeIds,
    terceirizadoEquipeNomes: terceirizadoEquipeNomes,
    materialUtilizadoIds: materialUtilizadoIds,
    houveParticipacaoOutroOrgao: orgaoParticipanteIds.isNotEmpty,
    orgaoParticipanteId: orgaoParticipanteId,
    orgaoParticipanteIds: orgaoParticipanteIds,
    status: 'rascunho',
    sincronizado: false,
  );
}
